In [64]:
import numpy as np

In [65]:
A=np.random.randn(1,3)
B=np.random.randn(3,3)

A = np.array([[1,1],[1,-1], [1,0]])

B = np.array([[2],[3], [1]])

In [66]:
print(A)

[[ 1  1]
 [ 1 -1]
 [ 1  0]]


In [67]:
print(B)

[[2]
 [3]
 [1]]


In [68]:
# Matrix Addition
addition = A + B
print("Addition:\n", addition)


Addition:
 [[3 3]
 [4 2]
 [2 1]]


In [69]:
# Matrix Subtraction
subtraction = A - B
print("Subtraction:\n", subtraction)


Subtraction:
 [[-1 -1]
 [-2 -4]
 [ 0 -1]]


In [70]:
# Element-wise Multiplication
element_wise_mult = A * B
print("Element-wise Multiplication:\n", element_wise_mult)


Element-wise Multiplication:
 [[ 2  2]
 [ 3 -3]
 [ 1  0]]


In [71]:
# Matrix Multiplication (Dot Product)
# WITH CURRENT DIMENSIONS YOU`LL GET AN ERROR

matrix_mult = A @ B  # or np.dot(A, B)
print("Matrix Multiplication:\n", matrix_mult)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [72]:
# LET`s CHANGE DIMENSIONS

C = np.array([[1, 1, -1]])

D = np.array([[2,3,4],[5,6,7], [8,9,0]])
print(C, '\n')
print(D, '\n')
matrix_mult = C @ D # or np.dot(C, D)
print("Matrix Multiplication:\n", matrix_mult)
print('Calculation logic is \n 1*2 + 1*3 + -1*4 = -1 ; \n 1*5 + 1*6 + -1*7 = 0 ; \n 1*8 + 1*9 + -1*0 = 11 ')

[[ 1  1 -1]] 

[[2 3 4]
 [5 6 7]
 [8 9 0]] 

Matrix Multiplication:
 [[-1  0 11]]
Calculation logic is 
 1*2 + 1*3 + -1*4 = -1 ; 
 1*5 + 1*6 + -1*7 = 0 ; 
 1*8 + 1*9 + -1*0 = 11 


In [73]:
# Transpose of a Matrix
transpose_A = A.T
print(" Matrix A:\n", A, '\n')
print("Transpose of A:\n", transpose_A)

 Matrix A:
 [[ 1  1]
 [ 1 -1]
 [ 1  0]] 

Transpose of A:
 [[ 1  1  1]
 [ 1 -1  0]]


**Determinant of a Matrix**
The determinant of a square matrix is a scalar value that provides key insights into the matrix's properties. It is denoted as det(A) or |A|.

Uses of Determinant
Invertibility: If det(A) ≠ 0, the matrix is invertible; otherwise, it's singular (non-invertible).

Solving Linear Systems: Used in Cramer's rule to solve Ax = B.

Geometric Interpretation: Represents the scaling factor of transformation (e.g., area in 2D, volume in 3D).

Eigenvalues & Stability: Helps analyze system stability in differential equations.



In [74]:
# Determinant of a Matrix
# ONLY SQUARED MATRIX

D = np.array([[2,3,4],[5,6,7], [8,9,0]])
det_D = np.linalg.det(D)
print("Determinant of A:", det_D)

Determinant of A: 29.99999999999999


In [75]:
# Inverse of a Matrix
inverse_D = np.linalg.inv(D) if det_D != 0 else "Not invertible"
print("Inverse of D:\n", inverse_D)

Inverse of D:
 [[-2.1         1.2        -0.1       ]
 [ 1.86666667 -1.06666667  0.2       ]
 [-0.1         0.2        -0.1       ]]


**Eigenvalues and Eigenvectors**
Eigenvalues and eigenvectors are fundamental concepts in linear algebra, widely used in machine learning, physics, and engineering.

**Eigenvalues **(λ): Scalars that represent how a transformation scales an eigenvector.

**Eigenvectors **(v): Nonzero vectors that remain in the same direction after a linear transformation.

Mathematically, they satisfy the equation:

𝐴𝑣=𝜆𝑣
where:

𝐴 is a square matrix,
𝑣 is an eigenvector,
𝜆 is the corresponding eigenvalue.

**Uses of Eigenvalues and Eigenvectors**
Dimensionality Reduction (e.g., PCA in machine learning).

*   Stability Analysis (in differential equations and dynamical systems).
*   Graph Theory (e.g., Google's PageRank algorithm).
*   Quantum Mechanics (e.g., representing quantum states).


In [76]:
# Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(D)
print("Eigenvalues of D:", eigenvalues, '\n')
print("Eigenvectors of D:\n", eigenvectors)

Eigenvalues of D: [14.77176409 -0.31451499 -6.4572491 ] 

Eigenvectors of D:
 [[-0.35811059 -0.74454495 -0.28091893]
 [-0.69852374  0.66417004 -0.38198454]
 [-0.61953321 -0.06731242  0.88043874]]


In [77]:
# Solving Dx = E (for a given E)
E_col = np.array([1, 2, 3])  # Example column vector
solution_x = np.linalg.solve(D, E_col)  # Solves Ax = B_col
print("Solution to Ax = B_col:\n", solution_x)


Solution to Ax = B_col:
 [0.         0.33333333 0.        ]
